trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.8.2'  # Or whichever version you want

steps:

# Terraform Installer task
- task: TerraformInstaller@1
  displayName: 'Install Terraform $(terraformVersion)'
  inputs:
    terraformVersion: '$(terraformVersion)'

# Terraform Init and Plan using AzureCLI task with WIF
- task: AzureCLI@2
  displayName: Terraform Init and Plan
  inputs:
    azureSubscription: 'WifSC'  # Replace with your actual service connection name
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Setting environment variables for Terraform..."
      export ARM_CLIENT_ID=$servicePrincipalId
      export ARM_TENANT_ID=$tenantId
      export ARM_SUBSCRIPTION_ID=$subscriptionId
      export ARM_OIDC_TOKEN=$(az account get-access-token --resource=https://management.azure.com --query accessToken -o tsv)

      terraform version
      terraform init
      terraform plan
