trigger:
  branches:
    include:
      - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.8.2'

steps:
  # Install Terraform
  - task: TerraformInstaller@1
    displayName: 'Install Terraform $(terraformVersion)'
    inputs:
      terraformVersion: '$(terraformVersion)'

  # Run Terraform Init and Plan using AzureCLI with WIF
  - task: AzureCLI@2
    displayName: 'Terraform Init and Plan'
    
    inputs:
      azureSubscription: 'wifsc'  # Your WIF-enabled service connection
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        echo "Setting environment variables for Terraform..."
        
        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_OIDC_TOKEN=$idToken
        export ARM_TENANT_ID=$tenantId
        export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        export ARM_USE_OIDC=true
        
        echo "Initializing Terraform..."
        terraform init
        
        echo "Running Terraform Plan..."
        terraform plan
 