trigger:
  branches:
    include:
      - main  # Adjust if using a different default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.8.2'

steps:
  # Install Terraform
  - task: TerraformInstaller@1
    displayName: 'Install Terraform $(terraformVersion)'
    inputs:
      terraformVersion: '$(terraformVersion)'

  # Run Terraform Init and Plan using AzureCLI with WIF
  - task: AzureCLI@2
    displayName: 'Terraform Init and Plan'
    inputs:
      azureSubscription: 'wifsc'  # Your WIF-enabled service connection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Setting environment variables for Terraform..."
        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_TENANT_ID=$tenantId
        export ARM_SUBSCRIPTION_ID=$subscriptionId
        export ARM_OIDC_TOKEN=$(az account get-access-token --resource=https://management.azure.com --query accessToken -o tsv)

        echo "Initializing Terraform..."
        terraform init

        echo "Running Terraform Plan..."
        terraform plan
 